### PR TITLE
Update firefoxDE

### PR DESCRIPTION
**Pull request by bwoods8**
Add spaces to firefoxDE name to match with the new installer

### CODE REVIEW

**Comment by gokulkrishh** [comment]
@bwoods8 Thanks for the PR. Pls, update the test as well.

**Comment by bwoods8** [comment]
Unless I am missing something, the test doesn't care about the name of the application bundle.

```
    it('should set firefox developer edition as default browser', () => {
      return setDefaultBrowser('firefoxDE');
    });
```

**Comment by gokulkrishh** [comment]
@bwoods8 Yep those tests are passing are not correct, see if you can make it work. Thanks

**Comment by bwoods8** [comment]
At first glance I saw this. This should make it work, though I would test to see if the application bundle is there first before running open (I wouldn't even run open).

**Comment by gokulkrishh** [comment]
@bwoods8 Updated and published as `set-default-browser@1.1.2`. Thanks for PR.

**Pull request merged**
